templateDir: crystal_client_templates
files:
  .ameba.yml: {}
  core.mustache:
    folder: src/
    destinationFilename: core.cr
    templateType: SupportingFiles
  ext/time.cr:
    folder: src/ext
    destinationFilename: time.cr
    templateType: SupportingFiles
  ext/primitive.cr:
    folder: src/ext
    destinationFilename: primitive.cr
    templateType: SupportingFiles
  ext/open_api/json.cr:
    folder: src/ext/open_api
    destinationFilename: json.cr
    templateType: SupportingFiles
  ext/open_api/validatable.cr:
    folder: src/ext/open_api
    destinationFilename: validatable.cr
    templateType: SupportingFiles
  spec/support/helpers.cr:
    folder: spec/support
    destinationFilename: helpers.cr
    templateType: SupportingFiles
  spec/support/vcr.cr:
    folder: spec/support
    destinationFilename: vcr.cr
    templateType: SupportingFiles
  spec/support/ext.cr:
    folder: spec/support
    destinationFilename: ext.cr
    templateType: SupportingFiles
  validators/enum_validator.cr:
    folder: src/validators
    destinationFilename: enum_validator.cr
    templateType: SupportingFiles
  validators/container_validator.cr:
    folder: src/validators
    destinationFilename: container_validator.cr
    templateType: SupportingFiles
  validators/primitive_validator.cr:
    folder: src/validators
    destinationFilename: primitive_validator.cr
    templateType: SupportingFiles
