openapi: 3.0.0
info:
  description: >-
    This spec is mainly for testing Petstore server and contains fake endpoints,
    models. Please do not use this for any other purpose. Special characters: "
    \
  version: 1.0.0
  title: OpenAPI Petstore
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: fake
paths:
  /fake:
    post:
      tags:
        - fake
      operationId: fake
      parameters:
        - name: id
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding:
              map_of_string:
                explode: true
                style: deepObject
              map_of_pet:
                explode: true
                style: deepObject
              map_of_map:
                explode: true
                style: deepObject
              map_of_array:
                explode: true
                style: deepObject
              inline_map:
                explode: true
                style: deepObject
            schema:
              type: object
              properties:
                map_of_string:
                  $ref: "#/components/schemas/map_of_string"
                map_of_pet:
                  $ref: "#/components/schemas/map_of_pet"
                map_of_map:
                  $ref: "#/components/schemas/map_of_map"
                map_of_array:
                  $ref: "#/components/schemas/map_of_array"
                inline_map:
                  type: object
                  additionalProperties:
                    type: string
      responses:
        "200":
          description: The instance started successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
servers:
  - url: https://localhost:8080/{version}
    description: The local server
    variables:
      version:
        enum:
          - "v1"
          - "v2"
        default: "v2"
  - url: https://127.0.0.1/no_variable
    description: The local server without variables
components:
  schemas:
    map_of_string:
      type: object
      additionalProperties:
        type: string
    map_of_pet:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/pet"
    map_of_map:
      type: object
      additionalProperties:
        type: object
        additionalProperties:
          type: string
    map_of_array:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    pet:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
